### PR TITLE
Make a start on a contributing file for the v2 runtime

### PR DESCRIPTION
**Pull request by wilsonge**
Start a contributing file for the 2.0 runtime as part of https://github.com/Azure/azure-functions-cli/issues/360 . Build instructions from what I’ve pieced together and contributing instructions adapted from the webjobs sdk repo

For the love of everything can we do something about the tests totally failing? Even if it means removing them for now?

Also includes writing up stuff found in that I could confirm on my macbook
- https://github.com/Azure/azure-functions-cli/issues/217
- https://github.com/Azure/azure-functions-cli/issues/283

### CODE REVIEW

**Comment by ahmelsayed** [comment]
Thanks @wilsonge! Tests should be fixed in master now.

**Comment by wilsonge** [comment]
@ahmelsayed i still can't seem to run anything on my macbook. after running `dotnet test` from source repo root I get (after the packages build - which I've skipped below to skip a tonne of debug output)

```
Build completed.

Test run for /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/bin/Debug/netcoreapp2.0/func.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/bin/Debug/netcoreapp2.0/func.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.

Build completed.

Test run for /Users/george/Sites/azure-functions-cli/test/Azure.Functions.Cli.Tests/bin/Debug/netcoreapp2.0/Azure.Functions.Cli.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in /Users/george/Sites/azure-functions-cli/test/Azure.Functions.Cli.Tests/bin/Debug/netcoreapp2.0/Azure.Functions.Cli.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

**Comment by ahmelsayed** [comment]
are you on latest master branch? this is what I get running `dotnet test` from the root (- the warnings) 

```
Build started, please wait...

Build completed.

Test run for D:\repos\azure-functions-cli\src\Azure.Functions.Cli\bin\Debug\netcoreapp2.0\func.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in D:\repos\azure-functions-cli\src\Azure.Functions.Cli\bin\Debug\netcoreapp2.0\func.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.

Test Run Aborted.
Build completed.

Test run for D:\repos\azure-functions-cli\test\Azure.Functions.Cli.Tests\bin\Debug\netcoreapp2.0\Azure.Functions.Cli.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:02.2153640]   Discovering: Azure.Functions.Cli.Tests
[xUnit.net 00:00:02.3761885]   Discovered:  Azure.Functions.Cli.Tests
[xUnit.net 00:00:02.3869736]   Starting:    Azure.Functions.Cli.Tests
[xUnit.net 00:00:03.2335604]   Finished:    Azure.Functions.Cli.Tests

Total tests: 51. Passed: 51. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 4.0370 Seconds
```

I changed the output dll name from `Azure.Functions.Cli.dll` to `func.dll`, but it looks like yours is still building the old one, which makes me thing you must still be on the core branch that I deleted.

**Comment by wilsonge** [comment]
A more complete output:

```
$ git remote -v
origin	git@github.com:wilsonge/azure-functions-cli.git (fetch)
origin	git@github.com:wilsonge/azure-functions-cli.git (push)
upstream	https://github.com/Azure/azure-functions-core-tools.git (fetch)
upstream	https://github.com/Azure/azure-functions-core-tools.git (push)
$ git fetch upstream
$ git merge upstream/master
Already up-to-date.
$ dotnet clean
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
$ dotnet test
Build started, please wait...
Build started, please wait...
Build completed.

Test run for /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/bin/Debug/netcoreapp2.0/func.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/bin/Debug/netcoreapp2.0/func.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.

Build completed.

Test run for /Users/george/Sites/azure-functions-cli/test/Azure.Functions.Cli.Tests/bin/Debug/netcoreapp2.0/Azure.Functions.Cli.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in /Users/george/Sites/azure-functions-cli/test/Azure.Functions.Cli.Tests/bin/Debug/netcoreapp2.0/Azure.Functions.Cli.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

**Comment by ahmelsayed** [comment]
what version of `dotnet` are you running? looking at the output from your command it says 

```
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
```

I'm running 2.1.4 and in my output on I get both on Windows and Linux

```
Microsoft (R) Test Execution Command Line Tool Version 15.5.0
```

There is apparently a couple of tests that are calling pinvoke and failing on Linux though. I'll fix them soon. but can you try updating your dotnet version?

**Comment by wilsonge** [comment]
```
 dotnet --version
2.0.0
```

I'll go see if I can find an update :)

**Comment by wilsonge** [comment]
OK That made a difference going to 2.1.4

```
Build completed.

Test run for /Users/george/Sites/azure-functions-cli/test/Azure.Functions.Cli.Tests/bin/Debug/netcoreapp2.0/Azure.Functions.Cli.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:06.0761940]   Discovering: Azure.Functions.Cli.Tests
[xUnit.net 00:00:06.2675710]   Discovered:  Azure.Functions.Cli.Tests
[xUnit.net 00:00:06.2864250]   Starting:    Azure.Functions.Cli.Tests
[xUnit.net 00:00:06.8822270]     Azure.Functions.Cli.Tests.ExtensionsTests.ProcessExtensionsTests.WaitForExitTest [FAIL]
[xUnit.net 00:00:06.8860060]       System.ComponentModel.Win32Exception : No such file or directory
[xUnit.net 00:00:06.8879510]       Stack Trace:
[xUnit.net 00:00:06.8902090]            at System.Diagnostics.Process.ResolvePath(String filename)
[xUnit.net 00:00:06.8903970]            at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
[xUnit.net 00:00:06.8905420]            at System.Diagnostics.Process.Start()
[xUnit.net 00:00:06.8906490]            at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
[xUnit.net 00:00:06.8908630]            at System.Diagnostics.Process.Start(String fileName)
[xUnit.net 00:00:06.8910280]         /Users/george/Sites/azure-functions-cli/test/Azure.Functions.Cli.Tests/ExtensionsTests/ProcessExtensionsTests.cs(18,0): at Azure.Functions.Cli.Tests.ExtensionsTests.ProcessExtensionsTests.<WaitForExitTest>d__0.MoveNext()
[xUnit.net 00:00:06.8913970]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:06.8915180]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:06.8916240]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:06.8922180]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:06.8923960]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:06.8925030]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:06.8926120]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:06.8926940]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:06.8927870]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:07.3240170]     Azure.Functions.Cli.Tests.ActionsTests.StartHostActionTests.CheckNonOptionalSettingsThrowsOnMissingAzureWebJobsStorage [FAIL]
[xUnit.net 00:00:07.3241710]       Expected type to be Azure.Functions.Cli.Common.CliException, but found System.IO.FileNotFoundException.
[xUnit.net 00:00:07.3242880]       Stack Trace:
[xUnit.net 00:00:07.3243780]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
[xUnit.net 00:00:07.3244510]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
[xUnit.net 00:00:07.3245180]            at FluentAssertions.Types.TypeAssertions.Be(Type expected, String because, Object[] becauseArgs)
[xUnit.net 00:00:07.3245860]            at FluentAssertions.Primitives.ReferenceTypeAssertions`2.BeOfType(Type expectedType, String because, Object[] becauseArgs)
[xUnit.net 00:00:07.3246470]            at FluentAssertions.Primitives.ReferenceTypeAssertions`2.BeOfType[T](String because, Object[] becauseArgs)
[xUnit.net 00:00:07.3247240]         /Users/george/Sites/azure-functions-cli/test/Azure.Functions.Cli.Tests/ActionsTests/StartHostActionTests.cs(41,0): at Azure.Functions.Cli.Tests.ActionsTests.StartHostActionTests.<CheckNonOptionalSettingsThrowsOnMissingAzureWebJobsStorage>d__0.MoveNext()
[xUnit.net 00:00:07.3248120]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:07.3248710]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:07.3249290]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:07.3249790]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:07.3250320]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:07.3250940]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:07.3251360]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:07.3251890]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:07.3252450]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   Azure.Functions.Cli.Tests.ExtensionsTests.ProcessExtensionsTests.WaitForExitTest
Error Message:
 System.ComponentModel.Win32Exception : No such file or directory
Stack Trace:
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at Azure.Functions.Cli.Tests.ExtensionsTests.ProcessExtensionsTests.<WaitForExitTest>d__0.MoveNext() in /Users/george/Sites/azure-functions-cli/test/Azure.Functions.Cli.Tests/ExtensionsTests/ProcessExtensionsTests.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   Azure.Functions.Cli.Tests.ActionsTests.StartHostActionTests.CheckNonOptionalSettingsThrowsOnMissingAzureWebJobsStorage
Error Message:
 Expected type to be Azure.Functions.Cli.Common.CliException, but found System.IO.FileNotFoundException.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Types.TypeAssertions.Be(Type expected, String because, Object[] becauseArgs)
   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.BeOfType(Type expectedType, String because, Object[] becauseArgs)
   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.BeOfType[T](String because, Object[] becauseArgs)
   at Azure.Functions.Cli.Tests.ActionsTests.StartHostActionTests.<CheckNonOptionalSettingsThrowsOnMissingAzureWebJobsStorage>d__0.MoveNext() in /Users/george/Sites/azure-functions-cli/test/Azure.Functions.Cli.Tests/ActionsTests/StartHostActionTests.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:07.3770030]     Azure.Functions.Cli.Tests.ActionsTests.StartHostActionTests.CheckNonOptionalSettingsPrintsWarningForMissingSettings [FAIL]
[xUnit.net 00:00:07.3771210]       System.IO.FileNotFoundException : Unable to find the specified file.
[xUnit.net 00:00:07.3772480]       Stack Trace:
[xUnit.net 00:00:07.3774360]            at Interop.Sys.GetCwdHelper(Byte* ptr, Int32 bufferSize)
[xUnit.net 00:00:07.3775500]            at Interop.Sys.GetCwd()
[xUnit.net 00:00:07.3776470]            at System.Environment.get_CurrentDirectory()
[xUnit.net 00:00:07.3778390]         /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/Common/SecretsManager.cs(27,0): at Azure.Functions.Cli.Common.SecretsManager.get_AppSettingsFilePath()
[xUnit.net 00:00:07.3780200]         /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/Common/SecretsManager.cs(41,0): at Azure.Functions.Cli.Common.SecretsManager.get_AppSettingsFileName()
[xUnit.net 00:00:07.3783190]         /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs(354,0): at Azure.Functions.Cli.Actions.HostActions.StartHostAction.<CheckNonOptionalSettings>d__48.MoveNext()
[xUnit.net 00:00:07.3784550]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:07.3785350]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:07.3786220]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:07.3787150]         /Users/george/Sites/azure-functions-cli/test/Azure.Functions.Cli.Tests/ActionsTests/StartHostActionTests.cs(87,0): at Azure.Functions.Cli.Tests.ActionsTests.StartHostActionTests.<CheckNonOptionalSettingsPrintsWarningForMissingSettings>d__2.MoveNext()
[xUnit.net 00:00:07.3788180]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:07.3788700]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:07.3789230]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:07.3789600]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:07.3790070]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:07.3790590]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:07.3790950]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:07.3791410]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:07.3791910]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   Azure.Functions.Cli.Tests.ActionsTests.StartHostActionTests.CheckNonOptionalSettingsPrintsWarningForMissingSettings
Error Message:
 System.IO.FileNotFoundException : Unable to find the specified file.
Stack Trace:
   at Interop.Sys.GetCwdHelper(Byte* ptr, Int32 bufferSize)
   at Interop.Sys.GetCwd()
   at System.Environment.get_CurrentDirectory()
   at Azure.Functions.Cli.Common.SecretsManager.get_AppSettingsFilePath() in /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/Common/SecretsManager.cs:line 27
   at Azure.Functions.Cli.Common.SecretsManager.get_AppSettingsFileName() in /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/Common/SecretsManager.cs:line 41
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.<CheckNonOptionalSettings>d__48.MoveNext() in /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs:line 354
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Functions.Cli.Tests.ActionsTests.StartHostActionTests.<CheckNonOptionalSettingsPrintsWarningForMissingSettings>d__2.MoveNext() in /Users/george/Sites/azure-functions-cli/test/Azure.Functions.Cli.Tests/ActionsTests/StartHostActionTests.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:07.9692820]     Azure.Functions.Cli.Tests.ActionsTests.ResolveActionTests.ResolveCommandLineCorrectly(args: "host start", type: typeof(Azure.Functions.Cli.Actions.HostActions.StartHostAction)) [FAIL]
[xUnit.net 00:00:07.9694760]       System.IO.FileNotFoundException : Unable to find the specified file.
[xUnit.net 00:00:07.9695640]       Stack Trace:
[xUnit.net 00:00:07.9696470]            at Interop.Sys.GetCwdHelper(Byte* ptr, Int32 bufferSize)
[xUnit.net 00:00:07.9697060]            at Interop.Sys.GetCwd()
[xUnit.net 00:00:07.9697640]            at System.Environment.get_CurrentDirectory()
[xUnit.net 00:00:07.9698460]         /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs(133,0): at Azure.Functions.Cli.Actions.HostActions.StartHostAction.<ParseArgs>b__40_8(String dir)
[xUnit.net 00:00:07.9699510]            at Fclp.FluentCommandLineParser.Parse(String[] args)
[xUnit.net 00:00:07.9700270]         /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs(137,0): at Azure.Functions.Cli.Actions.HostActions.StartHostAction.ParseArgs(String[] args)
[xUnit.net 00:00:07.9701290]         /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/ConsoleApp.cs(289,0): at Azure.Functions.Cli.ConsoleApp.Parse()
[xUnit.net 00:00:07.9701990]         /Users/george/Sites/azure-functions-cli/test/Azure.Functions.Cli.Tests/ActionsTests/ResolveActionTests.cs(64,0): at Azure.Functions.Cli.Tests.ActionsTests.ResolveActionTests.ResolveCommandLineCorrectly(String args, Type type)
Failed   Azure.Functions.Cli.Tests.ActionsTests.ResolveActionTests.ResolveCommandLineCorrectly(args: "host start", type: typeof(Azure.Functions.Cli.Actions.HostActions.StartHostAction))
Error Message:
 System.IO.FileNotFoundException : Unable to find the specified file.
Stack Trace:
   at Interop.Sys.GetCwdHelper(Byte* ptr, Int32 bufferSize)
   at Interop.Sys.GetCwd()
   at System.Environment.get_CurrentDirectory()
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.<ParseArgs>b__40_8(String dir) in /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs:line 133
   at Fclp.FluentCommandLineParser.Parse(String[] args)
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.ParseArgs(String[] args) in /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs:line 137
   at Azure.Functions.Cli.ConsoleApp.Parse() in /Users/george/Sites/azure-functions-cli/src/Azure.Functions.Cli/ConsoleApp.cs:line 289
   at Azure.Functions.Cli.Tests.ActionsTests.ResolveActionTests.ResolveCommandLineCorrectly(String args, Type type) in /Users/george/Sites/azure-functions-cli/test/Azure.Functions.Cli.Tests/ActionsTests/ResolveActionTests.cs:line 64
[xUnit.net 00:00:07.9934070]   Finished:    Azure.Functions.Cli.Tests

Total tests: 51. Passed: 47. Failed: 4. Skipped: 0.
Test Run Failed.
Test execution time: 10.1526 Seconds
```

**Comment by wilsonge** [comment]
I don't suppose there's a way you can find out what the minimum required dotnet core version is? Would be a useful addition to the contributing file :)

**Comment by ahmelsayed** [comment]
Yeah, I'll update the readme and contribution page. I'm entirely sure why 2.0.0 wasn't working but 2.1.4 is yet. I just happened to have that on my machine when I fixed the tests and I guess I didn't pay too much attention to the dotnet version. 

Thanks @wilsonge for catching that. I'll update the tests soon to fix the failed ones on linux.

**Comment by wilsonge** [comment]
Awesome :) Thanks!

**Pull request merged**
