### PR TITLE
Update readme to reflect installation for non-windows platforms

### PR DESCRIPTION
**Pull request by sdras**
Per Functions/CDA team meeting today to make this command more discoverable for Macs

### CODE REVIEW

**Comment by sdras** [comment]
cc @jeffhollan @eduardolaureano @simonaco

**Comment by nelak** [comment]
@sdras My 2cents the `core` tag installs the Azure functions cli 2.0.1-beta.22, while for windows it'll use the `latest` tag installing version 1.0.7. 
For users using the `core` tag it should be recommend that they enable the `beta` runtime in function app settings, or they may not see the same results as running locally.

**Comment by sdras** [comment]
@nelak ah, interesting, I wasn't aware of this, thank you for the clarification. I'll update it now.

**Comment by sdras** [comment]
Ok, updated. Let me know if you think that clarifies it. Thanks

**Comment by nelak** [comment]
Looks good to me :)

**Comment by jeffhollan** [comment]
Thanks @sdras - looks good to me as well. Can you also just add a link to the app setting tag to go to [this document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#target-the-version-20-runtime) which explains how to opt-in to beta version?  

Also @ahmelsayed will this update the [npm landing](https://www.npmjs.com/package/azure-functions-core-tools) page as well automatically?

**Comment by sdras** [comment]
Good call, @jeffhollan! Done. Please let me know if you need any further changes, or ready to merge if not.

**Pull request merged**
